# revision 32138
# category Package
# catalog-ctan /fonts/alegreya
# catalog-date 2013-11-13 19:38:17 +0100
# catalog-license ofl
# catalog-version undef
Name:		texlive-alegreya
Version:	20131113
Release:	3
Summary:	Alegreya fonts with LaTeX support
Group:		Publishing
URL:		http://www.ctan.org/tex-archive/fonts/alegreya
License:	OFL
Source0:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/alegreya.tar.xz
Source1:	http://mirrors.ctan.org/systems/texlive/tlnet/archive/alegreya.doc.tar.xz
BuildArch:	noarch
BuildRequires:	texlive-tlpkg
Requires(pre):	texlive-tlpkg
Requires(post):	texlive-kpathsea

%description
The Alegreya fonts are designed by Juan Pablo del Peral for
Huerta Tipografica. Alegreya is a typeface originally intended
for literature. It conveys a dynamic and varied rhythm which
facilitates the reading of long texts. The italic has just as
much care and attention to detail in the design as the roman.
Bold, black, small caps and five number styles are available.

%post
    %{_sbindir}/texlive.post

%postun
    if [ $1 -eq 0 ]; then
	%{_sbindir}/texlive.post
    fi

#-----------------------------------------------------------------------
%files
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_2thg7t.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_6gze5d.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_72lo2s.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_7levdp.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_7nunim.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_7p2ivs.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_atppps.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_b55zld.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_bft2rj.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_hghq3b.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_k3afeh.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_kf7dx2.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_lm7t5h.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_n534zq.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_nlrspr.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_prieif.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_qj6qbd.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_ry4sz3.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_sd6sdy.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_sutw7e.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_u55vgl.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_w6adhq.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_wtbjoa.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_x6hfhz.enc
%{_texmfdistdir}/fonts/enc/dvips/alegreya/algr_y5vbsk.enc
%{_texmfdistdir}/fonts/map/dvips/alegreya/alegreya.map
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Black-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BlackItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Bold-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-BoldItalic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Italic-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-lf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-lf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-lf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-lf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-lf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-lf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-lf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-sup-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-sup-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-sup-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-sup-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-sup-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tlf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tlf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tlf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tlf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tlf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tlf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tlf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tosf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tosf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tosf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tosf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tosf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tosf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/Alegreya-Regular-tosf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Black-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Black-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Black-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Black-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Black-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Black-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Black-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BlackItalic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BlackItalic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BlackItalic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BlackItalic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BlackItalic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BlackItalic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BlackItalic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Bold-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Bold-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Bold-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Bold-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Bold-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Bold-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Bold-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BoldItalic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BoldItalic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BoldItalic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BoldItalic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BoldItalic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BoldItalic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-BoldItalic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Italic-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Italic-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Italic-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Italic-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Italic-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Italic-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Italic-osf-ts1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Regular-osf-ly1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Regular-osf-ly1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Regular-osf-ot1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Regular-osf-t1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Regular-osf-t1.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Regular-osf-ts1--base.tfm
%{_texmfdistdir}/fonts/tfm/huerta/alegreya/AlegreyaSC-Regular-osf-ts1.tfm
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/Alegreya-Black.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/Alegreya-BlackItalic.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/Alegreya-Bold.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/Alegreya-BoldItalic.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/Alegreya-Italic.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/Alegreya-Regular.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/AlegreyaSC-Black.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/AlegreyaSC-BlackItalic.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/AlegreyaSC-Bold.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/AlegreyaSC-BoldItalic.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/AlegreyaSC-Italic.ttf
%{_texmfdistdir}/fonts/truetype/huerta/alegreya/AlegreyaSC-Regular.ttf
%{_texmfdistdir}/fonts/type1/huerta/alegreya/Alegreya-Black.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/Alegreya-BlackItalic.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/Alegreya-Bold.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/Alegreya-BoldItalic.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/Alegreya-Italic.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/Alegreya-Regular.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/AlegreyaSC-Black.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/AlegreyaSC-BlackItalic.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/AlegreyaSC-Bold.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/AlegreyaSC-BoldItalic.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/AlegreyaSC-Italic.pfb
%{_texmfdistdir}/fonts/type1/huerta/alegreya/AlegreyaSC-Regular.pfb
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-lf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-sup-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Black-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BlackItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-lf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-sup-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Bold-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-BoldItalic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-lf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-sup-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Italic-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-lf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-lf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-lf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-sup-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-sup-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-tlf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-tlf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-tlf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-tosf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-tosf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/Alegreya-Regular-tosf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Black-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Black-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Black-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-BlackItalic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-BlackItalic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-BlackItalic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Bold-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Bold-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Bold-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-BoldItalic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-BoldItalic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-BoldItalic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Italic-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Italic-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Italic-osf-ts1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Regular-osf-ly1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Regular-osf-t1.vf
%{_texmfdistdir}/fonts/vf/huerta/alegreya/AlegreyaSC-Regular-osf-ts1.vf
%{_texmfdistdir}/tex/latex/alegreya/LY1Alegreya-LF.fd
%{_texmfdistdir}/tex/latex/alegreya/LY1Alegreya-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/LY1Alegreya-Sup.fd
%{_texmfdistdir}/tex/latex/alegreya/LY1Alegreya-TLF.fd
%{_texmfdistdir}/tex/latex/alegreya/LY1Alegreya-TOsF.fd
%{_texmfdistdir}/tex/latex/alegreya/LY1AlegreyaSC-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/OT1Alegreya-LF.fd
%{_texmfdistdir}/tex/latex/alegreya/OT1Alegreya-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/OT1Alegreya-Sup.fd
%{_texmfdistdir}/tex/latex/alegreya/OT1Alegreya-TLF.fd
%{_texmfdistdir}/tex/latex/alegreya/OT1Alegreya-TOsF.fd
%{_texmfdistdir}/tex/latex/alegreya/OT1AlegreyaSC-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/T1Alegreya-LF.fd
%{_texmfdistdir}/tex/latex/alegreya/T1Alegreya-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/T1Alegreya-Sup.fd
%{_texmfdistdir}/tex/latex/alegreya/T1Alegreya-TLF.fd
%{_texmfdistdir}/tex/latex/alegreya/T1Alegreya-TOsF.fd
%{_texmfdistdir}/tex/latex/alegreya/T1AlegreyaSC-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/TS1Alegreya-LF.fd
%{_texmfdistdir}/tex/latex/alegreya/TS1Alegreya-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/TS1Alegreya-TLF.fd
%{_texmfdistdir}/tex/latex/alegreya/TS1Alegreya-TOsF.fd
%{_texmfdistdir}/tex/latex/alegreya/TS1AlegreyaSC-OsF.fd
%{_texmfdistdir}/tex/latex/alegreya/alegreya.sty
%doc %{_texmfdistdir}/doc/fonts/alegreya/OFL.txt
%doc %{_texmfdistdir}/doc/fonts/alegreya/README
%doc %{_texmfdistdir}/doc/fonts/alegreya/alegreya-samples.pdf
%doc %{_texmfdistdir}/doc/fonts/alegreya/alegreya-samples.tex

#-----------------------------------------------------------------------
%prep
%setup -c -a0 -a1

%build

%install
mkdir -p %{buildroot}%{_texmfdistdir}
cp -fpar fonts tex doc %{buildroot}%{_texmfdistdir}
